### ISSUE TITLE
Missing file: envmap.py

### ISSUE THREAD

**Issue by Jerrypiglet** [DiffusionLight/DiffusionLight-LoRA-Trainer#1]
Hi there, the file `envmap.py` seems to be missing, which includes functions/classes of `EnvironmentMap`, `rotation_matrix` which are needed in `train_lora_utils_final.py`. Would it be possible to upload this file as well? Thanks a lot!

**Comment by pureexe** [comment]
`envmap` is not a part of our code. It's a part of [skylibs](https://github.com/soravux/skylibs). 

You can install skylibs by using a command:

```
pip install skylibs
```

once you install skylibs, you can use `import envmap`

By the way, i recommend to setup our environment as [Installation guide](https://github.com/DiffusionLight/DiffusionLight/?tab=readme-ov-file#installation)

**Comment by Jerrypiglet** [comment]
Now I see the repo is sharing packages with the main repo. Thanks for the prompt response!
